var jsonData = {
	"reason":"查询成功",
	"result":{
		"title":"黑客帝国",
		"tag":"动作 / 恐怖 / 科幻",
		"act":"基努·李维斯 凯瑞·安·莫斯 劳伦斯·菲什伯恩 基努·里维斯 凯瑞-安·莫斯 雨果·维文 格洛丽亚·福斯特 乔·潘托里亚诺",
		"year":"1999",
		"rating":8.8,
		"area":"欧美",
		"dir":"安迪·沃卓斯基 / 拉里·沃卓斯基 / 拉娜·沃卓斯基 / Lana Wachowski",
		"desc":"基努李维斯又带来了一部令人兴奋的电影。本片被许多影评人评为1999年最棒的科幻影片。 在不久的将来，一名年轻的网络黑客尼奥基努李维斯发现看似正常的现实世界实际上是由一个名为“矩阵”的计算机人工智能系统控制的，人们就象他放牧的动物一样。尼奥在网络上查找关于“矩阵”的一切。在。在一名神秘女郎特蕾妮嘉丽安莫斯的引导下见到了黑客组织的首领摩菲斯劳伦斯费许本，三人一起走上了抗争“矩阵”的征途。 “尼奥，你曾经作过这样的梦吗，你坚信不移的东西都是真的吗？你能从那样的梦中醒来吗？你能分辨出梦境与现实世界的区别吗？”尼奥不顾一切地想追寻“矩阵”的真相，他在梦中总是听到关于它的耳语，这是一种神秘的不可知的东西，他清楚地感觉到自己正在受它的控制。 “矩阵是什么？”尼奥不知道，但是他相信摩菲斯这个在传说中被描绘成非常危险人物的黑客能够给他答案。 摩菲斯：“没有人能够说明矩阵是什么，你只有亲自去看。” 尼奥面对着另外一个问题：他就是它吗？虽然不知道为什么，尼奥的答案就是“不是”。摩菲斯的朋友塞弗同意他的观点。而其他人则不那么肯定。 另外，还有人在保护“矩阵”，冷酷的史密斯探员一伙掌握着令人震惊的秘密。 尼奥、默菲和特莱妮必须用他们的生命对抗强大的敌人来追寻答案、寻找自我。 他们的每一步都是危机四伏",
		"cover":"http://p2.qhimg.com/t01381f5f0577d6623e.jpg",
		"vdo_status":"none",
		"playlinks":{
			"sohu":"",
			"qq":"",
			"imgo":"",
			"youku":""
		},
		"video_rec":[
			{
				"cover":"http://p2.qhimg.com/d/dy_0c653ae1845ba1f0e41c7459ca91bd1e.jpg",
				"detail_url":"http://www.360kan.com/m/g6nlZBH3SHT7UR.html",
				"title":"黑客帝国3"
			},
			{
				"cover":"http://p4.qhimg.com/t01a03dbd37f4d256ca.jpg",
				"detail_url":"http://www.360kan.com/m/gqvpY0P8QXb0Sh.html",
				"title":"黑客帝国2：重装上阵"
			},
			{
				"cover":"http://p0.qhimg.com/t019a9da2d65b45f46b.jpg",
				"detail_url":"http://www.360kan.com/m/f6fkYkP8QXb0SR.html",
				"title":"黑客帝国3：矩阵革命"
			},
			{
				"cover":"http://p7.qhimg.com/d/dy_bc35854e1e5dca18bf68f5347ee009af.jpg",
				"detail_url":"http://www.360kan.com/m/gabnYhH2RXH4UB.html",
				"title":"黑客帝国：矩阵革命"
			},
			{
				"cover":"http://p1.qhimg.com/d/dy_8d02d9e235cc91cb572725c52a8a2a4c.jpg",
				"detail_url":"http://www.360kan.com/m/fqLqZETBQ0n0SB.html",
				"title":"网络杀人事件"
			}
		],
		"act_s":[
			{
				"name":"基努·李维斯",
				"url":null,
				"image":"http://p2.qhmsg.com/dmsmty/120_110_100/t010bde3034da69759d.jpg"
			},
			{
				"name":"凯瑞·安·莫斯",
				"url":null,
				"image":null
			},
			{
				"name":"劳伦斯·菲什伯恩",
				"url":null,
				"image":"http://p8.qhmsg.com/dmsmty/120_110_100/t01d60d34109959dd63.jpg"
			}
		]
	},
	"error_code":0
}
